server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/catalog_db
    username: postgres
    password: Nilesh@07

    hikari:
      minimum-idle: 2
      maximum-pool-size: 10

app:
  service-name: Catalog Service
  message: Catalog configuration loaded from GitHub
