
# secureshop-config-repository
server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: postgres
    password: Nilesh@07

    hikari:
      minimum-idle: 2
      maximum-pool-size: 10

app:
  service-name: Identity Service
  message: Identity configuration loaded from GitHub
